version: '3.8'

services:
  telegram-bot-api-server:
    build:
      context: ./tg-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      ALLOWED_BOT_IDS: ${ALLOWED_BOT_IDS}
      EXTRA_ARGS: "--local"
    restart: unless-stopped
    volumes:
      - telegram_api_data:/file
    networks:
      - bot_network

  music-bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    command: python -m src.core.main
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      TELEGRAM_API_URL: "http://telegram-bot-api-server:8080"
    depends_on:
      - telegram-bot-api-server
    restart: unless-stopped
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  telegram_api_data: 