# nixpacks.toml
# Configuration file for Railway's Nixpacks builder

# System packages are now handled by Dockerfile
# [phases.setup]
# aptPkgs = ["ffmpeg"]

# Define the command to start the application
[start]
cmd = "python main.py" 